global:
  scrape_interval: 15s
  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: 'core-api'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['core-api.railway.internal:80']

  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres.railway.internal:5432']
